FROM node:18 as build-step

RUN mkdir -p /app

WORKDIR /app

COPY ./package.json /app

RUN npm install

COPY . /app

RUN npm run build --env=prod

FROM nginx:1.21.6

COPY --from=build-step /app/dist/gymbros-angular /usr/share/nginx/html

EXPOSE 4200